### ISSUE TITLE
Unable to create hidden Paginator

### ISSUE THREAD

**Issue by refekt** [JUGADOR123/dinteractions-Paginator#18]
Is it possible to implement a hidden kwarg for the Paginator?

**Comment by JUGADOR123** [comment]
Yes, I will look into it in the coming hours

**Comment by Toricane** [comment]
Sorry for the late reply, but I don't think it will work since you can't edit ephemeral messages

**Comment by JUGADOR123** [comment]
yeah, sorry i totally forgot that you cannot edit hidden messages

**Comment by Toricane** [comment]
Sorry for this, but we just recently figured out how to edit hidden messages with `ComponentContext`, and a hidden arg/kwarg has been added in v1.2.3. Sorry for the inconvenience!

**Comment by g2asell2019** [comment]
> Sorry for this, but we just recently figured out how to edit hidden messages with `ComponentContext`, and a hidden arg/kwarg has been added in v1.2.3. Sorry for the inconvenience!

was you able to implement it?

**Comment by g2asell2019** [comment]
When I add `ephemeral=True` to this line [run()](https://github.com/interactions-py/paginator/blob/main/interactions/ext/paginator/paginator.py#L421)

You switch between page. When it's timeout, it will raise error,

`    raise LibraryException(message="You cannot edit a hidden message!", code=12)
interactions.api.error.LibraryException: An error occurred:
You cannot edit a hidden message!, with code '12' and severity '0'`

**Comment by EdVraz** [comment]
> When I add `ephemeral=True` to this line [run()](https://github.com/interactions-py/paginator/blob/main/interactions/ext/paginator/paginator.py#L421)
> 
> You switch between page. When it's timeout, it will raise error,
> 
> `    raise LibraryException(message="You cannot edit a hidden message!", code=12)
> interactions.api.error.LibraryException: An error occurred:
> You cannot edit a hidden message!, with code '12' and severity '0'`
> 

Yeah this is a discord limitation, it will not be possible to disable buttons on timeout because you can only edit the message after a button is pressed when the message is ephemeral

**Comment by g2asell2019** [comment]
I think it is not necessary to disable when message is ephemeral.
