### ISSUE TITLE
Paginator Index and pages linked 

### ISSUE THREAD

**Issue by refekt** [JUGADOR123/dinteractions-Paginator#26]
I'll call three separate commands that that closes with `await Paginator(...).run()` and all three commands buttons are linked. 

For example, I push "next" on the first command to go to 2/#. Then I push "next" while on 1/# on the second command and it goes to 3/#. 

Additionally, the `page` changes to the next page in the first Paginator called.

**Comment by Toricane** [comment]
Oh, you are right, lemme code a fix

**Comment by Toricane** [comment]
I fixed it, just added a random integer per paginator (a bit overkill: `self.random_id = randint(1, 999999999)`), and made all the `custom_id`s have it at the end, and check for it

**Comment by Toricane** [comment]
Is that too many numbers? should i decrease it to `999999`?

**Comment by Toricane** [comment]
Yeah I'm gonna decrease it, seems too unlikely 2 paginators will have the same number

**Comment by Toricane** [comment]
I'm gonna make a PR now, thanks for opening this issue!

**Comment by Toricane** [comment]
Check out #27
